# SYSTEM DEFINITION
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 11.0)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

# C++ COMPILER SETTINGS
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# BUILD SYSTEM TOOLS
set(CMAKE_C_COMPILER    "clang")
set(CMAKE_CXX_COMPILER  "clang++")
set(CMAKE_GENERATOR     "Ninja")
set(CMAKE_LINKER        "lld-link")
